# Python and Vectorization

## Vectorization
What is vectorization?
- <img src="./images/deep_31.png" alt="Drawing" style="width: 500px;"/>

In [9]:
import numpy as np
a = np.array([1,2,3,4])

# Comparing the time that the code will need
import time
a = np.random.rand(100000)
b = np.random.rand(100000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorization: {0}ms".format(str(toc-tic)))

# Will perform the same calc using the for loop
c=0
tic = time.time()
for i in range(100000):
    c += a[i] * b[i]
toc = time.time()
print(c)
print("For loop: {0}ms".format(str(toc-tic)))

Vectorization: 0.0002510547637939453ms
24988.848278606285
For loop: 0.0625920295715332ms


## More Vectorization Examples
- <img src="./images/deep_32.png" alt="Drawing" style="width: 500px;"/>
Always loook for a way to implement vectroization, nd avoid for looks at all cost.

## Vectorizing Logistic Regression
Noticed that we need to tranpose the weight to then calculate it with the values of each of the X vectors

We only need one line of code to find the result of Z.

<img src="./images/deep_33.png" alt="Drawing" style="width: 500px;"/>
- With vectorization, we can avoid using the for loops. Notice in the image, all the different z(1) and a(1) would have been computed at a for loop. We can use vectorization to find it with np.dot...
- We then ave to find the apporporiate vectorization of the sigmoid function

## Vectorizing Logistic Regression's Gradient Output
<img src="./images/deep_34.png" alt="Drawing" style="width: 300px;"/>

Noticed in the beginning, we find we have the actual and pred (image above)
The following is the for loop method when updating the gradient descent
- <img src="./images/deep_35.png" alt="Drawing" style="width: 300px;"/>
The following is the for vectorization method when updating the gradient descent
- <img src="./images/deep_36.png" alt="Drawing" style="width: 300px;"/>

Comparison of the code (how to use vectorization)
- <img src="./images/deep_37.png" alt="Drawing" style="width: 500px;"/>

## Broadcasting in Python
<img src="./images/deep_38.png" alt="Drawing" style="width: 500px;"/>

Looking at the image above, we are left to wonder can we find the percentage of each of the categories without having to do a for loop. Check the code below.

<img src="./images/deep_39.png" alt="Drawing" style="width: 500px;"/>
- Looking at the image above, we also find ourselves looking at other instances of when the broadcast of vector to matrix works.

General Principle:
- <img src="./images/deep_40.png" alt="Drawing" style="width: 500px;"/>

In [1]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [2]:
cal.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [3]:
percentage = 100*A/cal.reshape(1,4) # We need to reshape the vector to be of a matrix format
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

## A note on python/numpy vectors

In the code below, we will notice that there is a big different between an array without size (rank 1) and one of dimension of 1

- <img src="./images/deep_41.png" alt="Drawing" style="width: 500px;"/>

In [7]:
a = np.random.rand(5) # Gives us 5 value
b = np.random.rand(5,1) # though they are technically the same, they represent diff. things
print("Arrays:", a, b, "\n")
print("Shapes:", a.shape, b.shape, "\n")
print("Transpose:", a.T, b.T, "\n")

Arrays: [0.81653146 0.40323553 0.94636358 0.36687017 0.30011944] [[0.30921691]
 [0.21719689]
 [0.25356667]
 [0.45981542]
 [0.15422584]] 

Shapes: (5,) (5, 1) 

Transpose: [0.81653146 0.40323553 0.94636358 0.36687017 0.30011944] [[0.30921691 0.21719689 0.25356667 0.45981542 0.15422584]] 



## Explanation of logistic regression cost function (optional)
<img src="./images/deep_42.png" alt="Drawing" style="width: 500px;"/>
- Noticed how we can use the logistic regression and be able to simplfy the functions.

But one thing to realize is the in the image above, we are not using the log function. But if we do decide to add logs, then nothing should change (unless the intuition) since we will have to add the logs to both sides
- <img src="./images/deep_43.png" alt="Drawing" style="width: 500px;"/>


- Looking at the image below, we use the mult. for all the properties (x's) to find the prob of it happening (represented by 1)
-  We then look to minimize the cost function by finding the weights that will increase the maximum likelihood that we will find the lowest cost function
- <img src="./images/deep_44.png" alt="Drawing" style="width: 500px;"/>
